name: Auto Release ZIP
on:
  push:
    paths:
      - "Syncfusion/*.zip"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get newly added ZIP
        run: |
          FILE=$(git show --name-only --diff-filter=A --format="" ${{ github.sha }} -- 'Syncfusion/*.zip' | head -n 1)

          if [ -z "$FILE" ]; then
            FILE=$(ls -t Syncfusion/*.zip 2>/dev/null | head -n 1)
          fi

          if [ -z "$FILE" ]; then
            exit 1
          fi

          BASENAME=$(basename "$FILE")
          VERSION="${BASENAME%.zip}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "FILE=$FILE" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Syncfusion-${{ env.VERSION }}
          tag_name: Syncfusion-${{ env.VERSION }}
          files: ${{ env.FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
